# Generated by Django 2.2.2 on 2022-05-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220531_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='national_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
